import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import logo from '../../public/logo.efaf5a74.png'
import img1 from '../../public/img1.gif'
import img2 from '../../public/img2.webp'
import img3 from '../../public/img3.webp'
import styles from '@/styles/Home.module.css'
import Carousel from 'react-bootstrap/Carousel';

import { useState } from 'react';
import { HiAtSymbol, HiCalendar, HiLibrary, HiFingerPrint, HiOutlineUser, HiPhone } from 'react-icons/hi';
import { registerUser } from './api/firestore'


export default function Home() {
  const [user, setUser] = useState();
  const setData = (e) => {
    setUser((prev) => {
      return {
        ...prev,
        [e.target.name]: e.target.value,
      };
    })
  }
  const handleSubmit = async (e) => {
    e.preventDefault();
    const res = await registerUser(user);

    if (res) {
      console.log('success');
      const resFetch = await fetch('/api/sendgrid', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(user),
      });
    } else {
      console.log('error');
    }
  }

  return (
    <>
      <Head>
        <title>Book Session</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <main className='h-screen flex justify-between items-center '>
        <div className=''>

              <Image
                className="w-11/12 ml-10"
                src={img1}
                alt="First slide"
              />
  

        </div>
        <div className='h-screen bg-sky-100 flex-none'>
          <form className='flex flex-col gap-3 p-8 my-52 mx-64' onSubmit={handleSubmit} >
            <div className='flex justify-center items-center ml-28'>
              <Image src={logo} alt="Picture of the author" width="300" />
            </div>
            <div className={`${styles.input_group}`}>
              <input
                type="text"
                name='full_name'
                placeholder='Full Name'
                className={styles.input_text}
                onChange={(e) => setData(e)}
              />
              <span className='icon flex items-center px-4'>
                <HiOutlineUser size={25} />
              </span>
            </div>
            <div className={`${styles.input_group}`}>
              <input
                type="email"
                name='email'
                placeholder='Email'
                className={styles.input_text}
                onChange={(e) => setData(e)}
              />
              <span className='icon flex items-center px-4'>
                <HiAtSymbol size={25} />
              </span>
            </div>

            <div className={`${styles.input_group}`}>
              <input
                type="number"
                name='contact'
                placeholder='Contact'
                className={styles.input_text}
                onChange={(e) => setData(e)}
              />
              <span className='icon flex items-center px-4'>
                <HiPhone size={25} />
              </span>
            </div>


            <div className={`${styles.input_group}`}>
              <input
                type="date"
                name='date'
                placeholder='dd/mm/yyyy'
                className={styles.input_text}
                onChange={(e) => setData(e)}
              />
              <span className='icon flex items-center px-4'>
                <HiCalendar size={25} />
              </span>
            </div>
            <div className={`${styles.input_group}`}>
              <input
                type="text"
                name='school'
                placeholder='School'
                className={styles.input_text}
                onChange={(e) => setData(e)}
              />
              <span className='icon flex items-center px-4'>
                <HiLibrary size={25} />
              </span>
            </div>
            <button type='submit' className={styles.button}>
              Book Session
            </button>

          </form>
        </div>
      </main>
    </>
  )
}
