import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import logo from '../../public/logo.efaf5a74.png'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';
import { HiAtSymbol,HiCalendar,HiLibrary, HiFingerPrint, HiOutlineUser, HiPhone } from 'react-icons/hi';


export default function Home() {
  const [user, setUser] = useState();
  const setData = (e) => {
    setUser((prev) => {
      return {
        ...prev,
        [e.target.name]: e.target.value,
      };
    })
  }
  return (
    <>
      <Head>
        <title>Book Session</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <main className='h-screen flex justify-between items-center bg-sky-100'>
        <div className='h-screen shrink'>
          {/* <h1>hello daddy</h1> */}
        </div>
        <div className='h-screen bg-white flex-none'>
          <form className='flex flex-col gap-3 p-8 my-52 mx-72' >
            <div className='flex justify-center items-center ml-28'>
              <Image src={logo} alt="Picture of the author" width="300" />
            </div>
            <div className={`${styles.input_group}`}>
              <input
                type="text"
                name='full_name'
                placeholder='Full Name'
                className={styles.input_text}
                onChange={(e) => setData(e)}
              />
              <span className='icon flex items-center px-4'>
                <HiOutlineUser size={25} />
              </span>
            </div>
            <div className={`${styles.input_group}`}>
              <input
                type="email"
                name='email'
                placeholder='Email'
                className={styles.input_text}
                onChange={(e) => setData(e)}
              />
              <span className='icon flex items-center px-4'>
                <HiAtSymbol size={25} />
              </span>
            </div>

            <div className={`${styles.input_group}`}>
              <input
                type="number"
                name='contact'
                placeholder='Contact'
                className={styles.input_text}
                onChange={(e) => setData(e)}
              />
              <span className='icon flex items-center px-4'>
                <HiPhone size={25} />
              </span>
            </div>


            <div className={`${styles.input_group}`}>
              <input
                type="date"
                name='date'
                placeholder='dd/mm/yyyy'
                className={styles.input_text}
                onChange={(e) => setData(e)}
              />
              <span className='icon flex items-center px-4'>
                <HiCalendar size={25} />
              </span>
            </div>
            <div className={`${styles.input_group}`}>
              <input
                type="text"
                name='school'
                placeholder='School'
                className={styles.input_text}
                onChange={(e) => setData(e)}
              />
              <span className='icon flex items-center px-4'>
                <HiLibrary size={25} />
              </span>
            </div>
            {/* <div className='sh-btn'> */}
            <button type='submit' className={styles.button}>
              Book Session
            </button>
            {/* </div> */}
            
          </form>
        </div>
      </main>
    </>
  )
}
